sudo: false
language: python


# Test test matrix is spells out each supported version of Python explicitly:
matrix:
    include:
        -   python: 3.8
            env: TOXENV=codestyle

        -   python: 3.5
            env: TOXENV=py35
        -   python: 3.5
            env: TOXENV=py35-numba

        -   python: 3.6
            env: TOXENV=py36
        -   python: 3.6
            env: TOXENV=py36-numba

        -   python: 3.7
            env: TOXENV=py37
        -   python: 3.7
            env: TOXENV=py37-numba

        -   python: 3.8
            env: TOXENV=py38
        -   python: 3.8
            env: TOXENV=py38-numba

        -   python: pypy3
            env: TOXENV=pypy3
        -   python: pypy3
            env: TOXENV=pypy3-numba

allow_failures:
    # Tests with pypy are allowed to fail
    -   env: pypy3, pypy3-numba


install:
    - ./.travis/install.sh


script:
    - ./.travis/run.sh tox


#after_success:
#  - coverage combine
#  - coveralls


branches:
    only:
        - master
        - dev

notifications:
    email:
        recipients:
            - python@michelfe.it
        # options: [always|never|change] default: always
        on_success: always
        on_failure: always
        on_start: never
